/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaudePromptRequest
 */
export interface ClaudePromptRequest {
    /**
     * The text prompt to send to Claude AI
     * @type {string}
     * @memberof ClaudePromptRequest
     */
    prompt: string;
}

/**
 * Check if a given object implements the ClaudePromptRequest interface.
 */
export function instanceOfClaudePromptRequest(value: object): value is ClaudePromptRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function ClaudePromptRequestFromJSON(json: any): ClaudePromptRequest {
    return ClaudePromptRequestFromJSONTyped(json, false);
}

export function ClaudePromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaudePromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
    };
}

export function ClaudePromptRequestToJSON(json: any): ClaudePromptRequest {
    return ClaudePromptRequestToJSONTyped(json, false);
}

export function ClaudePromptRequestToJSONTyped(value?: ClaudePromptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
    };
}

