/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtractQuestionsJobStatusError
 */
export interface ExtractQuestionsJobStatusError {
    /**
     * 
     * @type {string}
     * @memberof ExtractQuestionsJobStatusError
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractQuestionsJobStatusError
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractQuestionsJobStatusError
     */
    details?: string;
}

/**
 * Check if a given object implements the ExtractQuestionsJobStatusError interface.
 */
export function instanceOfExtractQuestionsJobStatusError(value: object): value is ExtractQuestionsJobStatusError {
    return true;
}

export function ExtractQuestionsJobStatusErrorFromJSON(json: any): ExtractQuestionsJobStatusError {
    return ExtractQuestionsJobStatusErrorFromJSONTyped(json, false);
}

export function ExtractQuestionsJobStatusErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractQuestionsJobStatusError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ExtractQuestionsJobStatusErrorToJSON(json: any): ExtractQuestionsJobStatusError {
    return ExtractQuestionsJobStatusErrorToJSONTyped(json, false);
}

export function ExtractQuestionsJobStatusErrorToJSONTyped(value?: ExtractQuestionsJobStatusError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
    };
}

