/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtractQuestionsJobStatusResult
 */
export interface ExtractQuestionsJobStatusResult {
    /**
     * Path to generated files
     * @type {string}
     * @memberof ExtractQuestionsJobStatusResult
     */
    outputDirectory?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtractQuestionsJobStatusResult
     */
    questionsExtracted?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExtractQuestionsJobStatusResult
     */
    filesGenerated?: Array<string>;
}

/**
 * Check if a given object implements the ExtractQuestionsJobStatusResult interface.
 */
export function instanceOfExtractQuestionsJobStatusResult(value: object): value is ExtractQuestionsJobStatusResult {
    return true;
}

export function ExtractQuestionsJobStatusResultFromJSON(json: any): ExtractQuestionsJobStatusResult {
    return ExtractQuestionsJobStatusResultFromJSONTyped(json, false);
}

export function ExtractQuestionsJobStatusResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractQuestionsJobStatusResult {
    if (json == null) {
        return json;
    }
    return {
        
        'outputDirectory': json['outputDirectory'] == null ? undefined : json['outputDirectory'],
        'questionsExtracted': json['questionsExtracted'] == null ? undefined : json['questionsExtracted'],
        'filesGenerated': json['filesGenerated'] == null ? undefined : json['filesGenerated'],
    };
}

export function ExtractQuestionsJobStatusResultToJSON(json: any): ExtractQuestionsJobStatusResult {
    return ExtractQuestionsJobStatusResultToJSONTyped(json, false);
}

export function ExtractQuestionsJobStatusResultToJSONTyped(value?: ExtractQuestionsJobStatusResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outputDirectory': value['outputDirectory'],
        'questionsExtracted': value['questionsExtracted'],
        'filesGenerated': value['filesGenerated'],
    };
}

