/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtractQuestionsJobStatusProgress
 */
export interface ExtractQuestionsJobStatusProgress {
    /**
     * Current processing step
     * @type {string}
     * @memberof ExtractQuestionsJobStatusProgress
     */
    currentStep?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtractQuestionsJobStatusProgress
     */
    totalSteps?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtractQuestionsJobStatusProgress
     */
    completedSteps?: number;
    /**
     * Current page being processed
     * @type {number}
     * @memberof ExtractQuestionsJobStatusProgress
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtractQuestionsJobStatusProgress
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the ExtractQuestionsJobStatusProgress interface.
 */
export function instanceOfExtractQuestionsJobStatusProgress(value: object): value is ExtractQuestionsJobStatusProgress {
    return true;
}

export function ExtractQuestionsJobStatusProgressFromJSON(json: any): ExtractQuestionsJobStatusProgress {
    return ExtractQuestionsJobStatusProgressFromJSONTyped(json, false);
}

export function ExtractQuestionsJobStatusProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractQuestionsJobStatusProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'currentStep': json['currentStep'] == null ? undefined : json['currentStep'],
        'totalSteps': json['totalSteps'] == null ? undefined : json['totalSteps'],
        'completedSteps': json['completedSteps'] == null ? undefined : json['completedSteps'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function ExtractQuestionsJobStatusProgressToJSON(json: any): ExtractQuestionsJobStatusProgress {
    return ExtractQuestionsJobStatusProgressToJSONTyped(json, false);
}

export function ExtractQuestionsJobStatusProgressToJSONTyped(value?: ExtractQuestionsJobStatusProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentStep': value['currentStep'],
        'totalSteps': value['totalSteps'],
        'completedSteps': value['completedSteps'],
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
    };
}

