/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Paper } from './Paper';
import {
    PaperFromJSON,
    PaperFromJSONTyped,
    PaperToJSON,
    PaperToJSONTyped,
} from './Paper';

/**
 * Represents the structure of a pack with its papers and sections
 * @export
 * @interface PackStructureResponse
 */
export interface PackStructureResponse {
    /**
     * ID of the pack
     * @type {string}
     * @memberof PackStructureResponse
     */
    packId?: string;
    /**
     * Title of the pack
     * @type {string}
     * @memberof PackStructureResponse
     */
    packTitle?: string;
    /**
     * Type of the pack
     * @type {string}
     * @memberof PackStructureResponse
     */
    packType?: string;
    /**
     * List of papers in this pack
     * @type {Array<Paper>}
     * @memberof PackStructureResponse
     */
    papers?: Array<Paper>;
}

/**
 * Check if a given object implements the PackStructureResponse interface.
 */
export function instanceOfPackStructureResponse(value: object): value is PackStructureResponse {
    return true;
}

export function PackStructureResponseFromJSON(json: any): PackStructureResponse {
    return PackStructureResponseFromJSONTyped(json, false);
}

export function PackStructureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackStructureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'packId': json['packId'] == null ? undefined : json['packId'],
        'packTitle': json['packTitle'] == null ? undefined : json['packTitle'],
        'packType': json['packType'] == null ? undefined : json['packType'],
        'papers': json['papers'] == null ? undefined : ((json['papers'] as Array<any>).map(PaperFromJSON)),
    };
}

export function PackStructureResponseToJSON(json: any): PackStructureResponse {
    return PackStructureResponseToJSONTyped(json, false);
}

export function PackStructureResponseToJSONTyped(value?: PackStructureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'packId': value['packId'],
        'packTitle': value['packTitle'],
        'packType': value['packType'],
        'papers': value['papers'] == null ? undefined : ((value['papers'] as Array<any>).map(PaperToJSON)),
    };
}

