/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionResponse } from './QuestionResponse';
import {
    QuestionResponseFromJSON,
    QuestionResponseFromJSONTyped,
    QuestionResponseToJSON,
    QuestionResponseToJSONTyped,
} from './QuestionResponse';

/**
 * 
 * @export
 * @interface PagedQuestions
 */
export interface PagedQuestions {
    /**
     * Total number of elements matching the criteria
     * @type {number}
     * @memberof PagedQuestions
     */
    totalElements?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PagedQuestions
     */
    totalPages?: number;
    /**
     * Number of elements per page
     * @type {number}
     * @memberof PagedQuestions
     */
    pageSize?: number;
    /**
     * Current page number (1-based)
     * @type {number}
     * @memberof PagedQuestions
     */
    pageNumber?: number;
    /**
     * Indicates if this is the last page
     * @type {boolean}
     * @memberof PagedQuestions
     */
    last?: boolean;
    /**
     * Indicates if this is the first page
     * @type {boolean}
     * @memberof PagedQuestions
     */
    first?: boolean;
    /**
     * List of questions
     * @type {Array<QuestionResponse>}
     * @memberof PagedQuestions
     */
    content?: Array<QuestionResponse>;
}

/**
 * Check if a given object implements the PagedQuestions interface.
 */
export function instanceOfPagedQuestions(value: object): value is PagedQuestions {
    return true;
}

export function PagedQuestionsFromJSON(json: any): PagedQuestions {
    return PagedQuestionsFromJSONTyped(json, false);
}

export function PagedQuestionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedQuestions {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'last': json['last'] == null ? undefined : json['last'],
        'first': json['first'] == null ? undefined : json['first'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(QuestionResponseFromJSON)),
    };
}

export function PagedQuestionsToJSON(json: any): PagedQuestions {
    return PagedQuestionsToJSONTyped(json, false);
}

export function PagedQuestionsToJSONTyped(value?: PagedQuestions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
        'last': value['last'],
        'first': value['first'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(QuestionResponseToJSON)),
    };
}

