/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PackResponse } from './PackResponse';
import {
    PackResponseFromJSON,
    PackResponseFromJSONTyped,
    PackResponseToJSON,
    PackResponseToJSONTyped,
} from './PackResponse';

/**
 * 
 * @export
 * @interface PagedPackResponse
 */
export interface PagedPackResponse {
    /**
     * Total number of elements matching the criteria
     * @type {number}
     * @memberof PagedPackResponse
     */
    totalElements?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PagedPackResponse
     */
    totalPages?: number;
    /**
     * Number of elements per page
     * @type {number}
     * @memberof PagedPackResponse
     */
    pageSize?: number;
    /**
     * Current page number (1-based)
     * @type {number}
     * @memberof PagedPackResponse
     */
    pageNumber?: number;
    /**
     * Indicates if this is the last page
     * @type {boolean}
     * @memberof PagedPackResponse
     */
    last?: boolean;
    /**
     * Indicates if this is the first page
     * @type {boolean}
     * @memberof PagedPackResponse
     */
    first?: boolean;
    /**
     * 
     * @type {Array<PackResponse>}
     * @memberof PagedPackResponse
     */
    content?: Array<PackResponse>;
}

/**
 * Check if a given object implements the PagedPackResponse interface.
 */
export function instanceOfPagedPackResponse(value: object): value is PagedPackResponse {
    return true;
}

export function PagedPackResponseFromJSON(json: any): PagedPackResponse {
    return PagedPackResponseFromJSONTyped(json, false);
}

export function PagedPackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedPackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'last': json['last'] == null ? undefined : json['last'],
        'first': json['first'] == null ? undefined : json['first'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PackResponseFromJSON)),
    };
}

export function PagedPackResponseToJSON(json: any): PagedPackResponse {
    return PagedPackResponseToJSONTyped(json, false);
}

export function PagedPackResponseToJSONTyped(value?: PagedPackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
        'last': value['last'],
        'first': value['first'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PackResponseToJSON)),
    };
}

