/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationResponse } from './NotificationResponse';
import {
    NotificationResponseFromJSON,
    NotificationResponseFromJSONTyped,
    NotificationResponseToJSON,
    NotificationResponseToJSONTyped,
} from './NotificationResponse';

/**
 * 
 * @export
 * @interface PagedNotifications
 */
export interface PagedNotifications {
    /**
     * Total number of elements matching the criteria
     * @type {number}
     * @memberof PagedNotifications
     */
    totalElements?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PagedNotifications
     */
    totalPages?: number;
    /**
     * Number of elements per page
     * @type {number}
     * @memberof PagedNotifications
     */
    pageSize?: number;
    /**
     * Current page number (1-based)
     * @type {number}
     * @memberof PagedNotifications
     */
    pageNumber?: number;
    /**
     * Indicates if this is the last page
     * @type {boolean}
     * @memberof PagedNotifications
     */
    last?: boolean;
    /**
     * Indicates if this is the first page
     * @type {boolean}
     * @memberof PagedNotifications
     */
    first?: boolean;
    /**
     * List of notifications
     * @type {Array<NotificationResponse>}
     * @memberof PagedNotifications
     */
    content?: Array<NotificationResponse>;
}

/**
 * Check if a given object implements the PagedNotifications interface.
 */
export function instanceOfPagedNotifications(value: object): value is PagedNotifications {
    return true;
}

export function PagedNotificationsFromJSON(json: any): PagedNotifications {
    return PagedNotificationsFromJSONTyped(json, false);
}

export function PagedNotificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedNotifications {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'last': json['last'] == null ? undefined : json['last'],
        'first': json['first'] == null ? undefined : json['first'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(NotificationResponseFromJSON)),
    };
}

export function PagedNotificationsToJSON(json: any): PagedNotifications {
    return PagedNotificationsToJSONTyped(json, false);
}

export function PagedNotificationsToJSONTyped(value?: PagedNotifications | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
        'last': value['last'],
        'first': value['first'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(NotificationResponseToJSON)),
    };
}

