/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Activity } from './Activity';
import {
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
    ActivityToJSONTyped,
} from './Activity';

/**
 * 
 * @export
 * @interface PagedActivities
 */
export interface PagedActivities {
    /**
     * Total number of elements matching the criteria
     * @type {number}
     * @memberof PagedActivities
     */
    totalElements?: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PagedActivities
     */
    totalPages?: number;
    /**
     * Number of elements per page
     * @type {number}
     * @memberof PagedActivities
     */
    pageSize?: number;
    /**
     * Current page number (1-based)
     * @type {number}
     * @memberof PagedActivities
     */
    pageNumber?: number;
    /**
     * Indicates if this is the last page
     * @type {boolean}
     * @memberof PagedActivities
     */
    last?: boolean;
    /**
     * Indicates if this is the first page
     * @type {boolean}
     * @memberof PagedActivities
     */
    first?: boolean;
    /**
     * List of activities
     * @type {Array<Activity>}
     * @memberof PagedActivities
     */
    content?: Array<Activity>;
}

/**
 * Check if a given object implements the PagedActivities interface.
 */
export function instanceOfPagedActivities(value: object): value is PagedActivities {
    return true;
}

export function PagedActivitiesFromJSON(json: any): PagedActivities {
    return PagedActivitiesFromJSONTyped(json, false);
}

export function PagedActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedActivities {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'last': json['last'] == null ? undefined : json['last'],
        'first': json['first'] == null ? undefined : json['first'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ActivityFromJSON)),
    };
}

export function PagedActivitiesToJSON(json: any): PagedActivities {
    return PagedActivitiesToJSONTyped(json, false);
}

export function PagedActivitiesToJSONTyped(value?: PagedActivities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'pageNumber': value['pageNumber'],
        'last': value['last'],
        'first': value['first'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ActivityToJSON)),
    };
}

