/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicPracticeRecommendations
 */
export interface TopicPracticeRecommendations {
    /**
     * Topics that need more practice
     * @type {Array<string>}
     * @memberof TopicPracticeRecommendations
     */
    practiceMore: Array<string>;
    /**
     * Recommendation for next practice session
     * @type {string}
     * @memberof TopicPracticeRecommendations
     */
    nextSession: string;
}

/**
 * Check if a given object implements the TopicPracticeRecommendations interface.
 */
export function instanceOfTopicPracticeRecommendations(value: object): value is TopicPracticeRecommendations {
    if (!('practiceMore' in value) || value['practiceMore'] === undefined) return false;
    if (!('nextSession' in value) || value['nextSession'] === undefined) return false;
    return true;
}

export function TopicPracticeRecommendationsFromJSON(json: any): TopicPracticeRecommendations {
    return TopicPracticeRecommendationsFromJSONTyped(json, false);
}

export function TopicPracticeRecommendationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicPracticeRecommendations {
    if (json == null) {
        return json;
    }
    return {
        
        'practiceMore': json['practiceMore'],
        'nextSession': json['nextSession'],
    };
}

export function TopicPracticeRecommendationsToJSON(json: any): TopicPracticeRecommendations {
    return TopicPracticeRecommendationsToJSONTyped(json, false);
}

export function TopicPracticeRecommendationsToJSONTyped(value?: TopicPracticeRecommendations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'practiceMore': value['practiceMore'],
        'nextSession': value['nextSession'],
    };
}

