/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateQuestionAttemptRequest
 */
export interface UpdateQuestionAttemptRequest {
    /**
     * ID of the attempt being updated
     * @type {number}
     * @memberof UpdateQuestionAttemptRequest
     */
    attemptId: number;
    /**
     * ID of the question being updated
     * @type {number}
     * @memberof UpdateQuestionAttemptRequest
     */
    questionId: number;
    /**
     * Index of the question in the practice session
     * @type {number}
     * @memberof UpdateQuestionAttemptRequest
     */
    questionIndex?: number;
    /**
     * The student's answer (text for open-ended, option text for MCQ)
     * @type {string}
     * @memberof UpdateQuestionAttemptRequest
     */
    studentAnswer?: string;
    /**
     * For MCQ questions, the ID of the selected option
     * @type {number}
     * @memberof UpdateQuestionAttemptRequest
     */
    selectedOptionId?: number;
    /**
     * Time spent on this question
     * @type {number}
     * @memberof UpdateQuestionAttemptRequest
     */
    timeSpentSeconds: number;
    /**
     * Array of working steps showing the student's work process
     * @type {Array<string>}
     * @memberof UpdateQuestionAttemptRequest
     */
    studentWorkingSteps?: Array<string>;
    /**
     * Action to perform - either submit an answer or skip the question
     * @type {string}
     * @memberof UpdateQuestionAttemptRequest
     */
    action: UpdateQuestionAttemptRequestActionEnum;
}


/**
 * @export
 */
export const UpdateQuestionAttemptRequestActionEnum = {
    Answer: 'ANSWER',
    Skip: 'SKIP'
} as const;
export type UpdateQuestionAttemptRequestActionEnum = typeof UpdateQuestionAttemptRequestActionEnum[keyof typeof UpdateQuestionAttemptRequestActionEnum];


/**
 * Check if a given object implements the UpdateQuestionAttemptRequest interface.
 */
export function instanceOfUpdateQuestionAttemptRequest(value: object): value is UpdateQuestionAttemptRequest {
    if (!('attemptId' in value) || value['attemptId'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('timeSpentSeconds' in value) || value['timeSpentSeconds'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function UpdateQuestionAttemptRequestFromJSON(json: any): UpdateQuestionAttemptRequest {
    return UpdateQuestionAttemptRequestFromJSONTyped(json, false);
}

export function UpdateQuestionAttemptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateQuestionAttemptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attemptId': json['attemptId'],
        'questionId': json['questionId'],
        'questionIndex': json['questionIndex'] == null ? undefined : json['questionIndex'],
        'studentAnswer': json['studentAnswer'] == null ? undefined : json['studentAnswer'],
        'selectedOptionId': json['selectedOptionId'] == null ? undefined : json['selectedOptionId'],
        'timeSpentSeconds': json['timeSpentSeconds'],
        'studentWorkingSteps': json['studentWorkingSteps'] == null ? undefined : json['studentWorkingSteps'],
        'action': json['action'],
    };
}

export function UpdateQuestionAttemptRequestToJSON(json: any): UpdateQuestionAttemptRequest {
    return UpdateQuestionAttemptRequestToJSONTyped(json, false);
}

export function UpdateQuestionAttemptRequestToJSONTyped(value?: UpdateQuestionAttemptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attemptId': value['attemptId'],
        'questionId': value['questionId'],
        'questionIndex': value['questionIndex'],
        'studentAnswer': value['studentAnswer'],
        'selectedOptionId': value['selectedOptionId'],
        'timeSpentSeconds': value['timeSpentSeconds'],
        'studentWorkingSteps': value['studentWorkingSteps'],
        'action': value['action'],
    };
}

