/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePracticeSessionRequest
 */
export interface UpdatePracticeSessionRequest {
    /**
     * Update current question index
     * @type {number}
     * @memberof UpdatePracticeSessionRequest
     */
    currentQuestionIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePracticeSessionRequest
     */
    status?: UpdatePracticeSessionRequestStatusEnum;
    /**
     * Update total time spent
     * @type {number}
     * @memberof UpdatePracticeSessionRequest
     */
    totalTimeSpentSeconds?: number;
}


/**
 * @export
 */
export const UpdatePracticeSessionRequestStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    Abandoned: 'ABANDONED'
} as const;
export type UpdatePracticeSessionRequestStatusEnum = typeof UpdatePracticeSessionRequestStatusEnum[keyof typeof UpdatePracticeSessionRequestStatusEnum];


/**
 * Check if a given object implements the UpdatePracticeSessionRequest interface.
 */
export function instanceOfUpdatePracticeSessionRequest(value: object): value is UpdatePracticeSessionRequest {
    return true;
}

export function UpdatePracticeSessionRequestFromJSON(json: any): UpdatePracticeSessionRequest {
    return UpdatePracticeSessionRequestFromJSONTyped(json, false);
}

export function UpdatePracticeSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePracticeSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentQuestionIndex': json['currentQuestionIndex'] == null ? undefined : json['currentQuestionIndex'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalTimeSpentSeconds': json['totalTimeSpentSeconds'] == null ? undefined : json['totalTimeSpentSeconds'],
    };
}

export function UpdatePracticeSessionRequestToJSON(json: any): UpdatePracticeSessionRequest {
    return UpdatePracticeSessionRequestToJSONTyped(json, false);
}

export function UpdatePracticeSessionRequestToJSONTyped(value?: UpdatePracticeSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentQuestionIndex': value['currentQuestionIndex'],
        'status': value['status'],
        'totalTimeSpentSeconds': value['totalTimeSpentSeconds'],
    };
}

