/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * This API exposes endpoints to manage entities and items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ImportSyllabusDataRequest {
    jsonFilePath?: string;
}

/**
 * 
 */
export class SyllabusImportControllerApi extends runtime.BaseAPI {

    /**
     */
    async importDefaultSyllabusDataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/import/default`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async importDefaultSyllabusData(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.importDefaultSyllabusDataRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async importSyllabusDataRaw(requestParameters: ImportSyllabusDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['jsonFilePath'] != null) {
            queryParameters['jsonFilePath'] = requestParameters['jsonFilePath'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/import`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async importSyllabusData(requestParameters: ImportSyllabusDataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.importSyllabusDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
